from __future__ import annotations

"""
Markdown report generator for daily AI trend reports.
"""

from datetime import date
from pathlib import Path
from typing import Optional

from config import settings
from src.models import DailyReport, RepoData


def generate_markdown(report: DailyReport) -> str:
    """Generate a Markdown-formatted daily trend report."""
    lines = []

    # Title
    lines.append(f"# 📊 AI Trend Daily — {report.date}")
    lines.append("")
    lines.append(
        f"> 🤖 AI 开源项目每日趋势报告 | "
        f"Generated: {report.generated_at[:10]}"
    )
    lines.append("")

    # Executive summary section
    lines.append("## 📈 今日概览")
    lines.append("")
    lines.append(
        f"| 指标 | 数值 |"
    )
    lines.append(
        f"|------|------|"
    )
    lines.append(
        f"| 收录项目总数 | {report.total_repos} |"
    )
    lines.append(
        f"| AI 相关项目 | {report.total_ai_repos} |"
    )
    lines.append(
        f"| AI 分类数 | {len(report.categories)} |"
    )
    lines.append(
        f"| 编程语言 | {len(report.languages)} |"
    )
    lines.append("")

    # Insight
    if report.insight_zh:
        lines.append("### 🤖 AI 今日洞察")
        lines.append("")
        lines.append(f"> {report.insight_zh}")
        lines.append("")

    # AI Category distribution
    lines.append("## 🏷️ AI 子领域分布")
    lines.append("")
    lines.append("| 分类 | 数量 | 占比 |")
    lines.append("|------|------|------|")
    for cat in report.categories:
        bar = "█" * max(1, int(cat.percentage / 3))
        lines.append(f"| {cat.name} | {cat.count} | {cat.percentage}% {bar} |")
    lines.append("")

    # Top repos
    if report.top_repos:
        lines.append("## 🔥 今日热门 Top 10")
        lines.append("")
        for repo in report.top_repos[:10]:
            lines.append(_repo_to_md(repo))
        lines.append("")

    # Top gainers
    if report.top_gainers:
        lines.append("## ⚡ Star 增长最快")
        lines.append("")
        for repo in report.top_gainers[:5]:
            lines.append(
                f"- **[{repo.name}]({repo.url})** → ⭐ +{repo.stars_today}/天 "
                f"(分类: {repo.ai_category})"
            )
        lines.append("")

    # New entrants
    if report.new_entrants:
        lines.append("## 🆕 新星项目（首次上榜）")
        lines.append("")
        for repo in report.new_entrants[:5]:
            lines.append(
                f"- **[{repo.name}]({repo.url})** — ⭐ {repo.stars} "
                f"(+{repo.stars_today}/天)"
            )
            lines.append(f"  - {repo.description[:100]}")
        lines.append("")

    # Language distribution
    if report.languages:
        lines.append("## 💻 编程语言分布")
        lines.append("")
        lines.append("| 语言 | 项目数 | 占比 |")
        lines.append("|------|--------|------|")
        for lang in report.languages[:8]:
            bar = "█" * max(1, int(lang.percentage / 4))
            lines.append(f"| {lang.name} | {lang.count} | {lang.percentage}% {bar} |")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append(
        f"_Generated by [AI Trend Daily](https://github.com/liuyang/firstblood) "
        f"on {report.generated_at[:19]}_"
    )
    lines.append("")

    return "\n".join(lines)


def _repo_to_md(repo: RepoData, index: int = 0) -> str:
    """Format a single repo as Markdown."""
    rank_display = f"#{repo.rank}" if repo.rank else f"#{index + 1}"
    topics_str = " · ".join(
        f"`{t}`" for t in [repo.ai_category] + repo.ai_subcategories[:2]
    )
    stars_display = (
        f"⭐ {repo.stars:,} (+{repo.stars_today}/天)"
        if repo.stars_today
        else f"⭐ {repo.stars:,}"
    )

    lines = [
        f"### {rank_display} [{repo.name}]({repo.url})",
        f"📦 {stars_display}  🍴 {repo.forks:,}"
        f"  🔤 {repo.language or 'N/A'}",
        f"🏷️ {topics_str}",
        f"{repo.description[:150]}" if repo.description else "",
    ]

    if repo.summary_zh:
        lines.append(f"> 💡 {repo.summary_zh}")

    return "\n\n".join(filter(None, lines)) + "\n"
